<tr data-id="<?php echo $this->model->ID; ?>">
    <td><?php echo $this->model->ID; ?></td>
    <td><?php echo $this->model->get('name'); ?></td>
    <td>
        <a href="/admin/services/edit/id/<?php echo $this->model->ID; ?>" title="Редактировать"><i class="icon-pencil"></i></a>
        <a href="/admin/services/del/id/<?php echo $this->model->ID;?>" class="remove-srv" title="Удалить"><i class="icon-remove"></i></a>
    </td>
</tr>