<ul class="breadcrumb">
    <li><a href="/admin">Главная</a> <span class="divider">/</span></li>
    <li><span>Онлайн помощь</span></li>
</ul>
<h3>Онлайн помощь</h3>
<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" WIDTH="700" HEIGHT="370" id="as" ALIGN="">
<PARAM NAME=movie VALUE="as.swf">
<PARAM NAME=quality VALUE=High> 
<PARAM NAME=bgcolor VALUE=#ece9d8> 
<EMBED src="as.swf" quality=High bgcolor=#ece9d8 WIDTH="550" HEIGHT="370" NAME="as" ALIGN="" TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer"></EMBED></OBJECT>