<div id="you_here"><p><span><?php echo $this->translate('You are here')?></span>
<a href="/"><?php echo $this->translate('Home'); ?></a> / <?php echo $this->translate('About us')?></p></div>
<div id="menu_view">
    <div id="line"></div>
</div>

<div class="pages">
    <?php //echo $this->text->get('text'); ?>
    
<div id="about">
<div class="about1">    
<div id="mapa"><img src="/img/map_rus.jpg" alt=""></div>
<div class="info1">
<p><span><?php echo $this->translate('Director');?>:</span><br>
Наталия Панкова</p>
<p><span><?php echo $this->translate('Meneger');?>:</span><br>
Татьяна, Кристина</p>
<p><span><?php echo $this->translate('Our adress');?>:</span><br>
ул. Сумская 13,<br>
2-й этаж, офис 3<br>
Харьков<br> 
Украина<br><br>
</p>
<p><span><?php echo $this->translate('Our work hours');?>:</span><br>
Понедельник - суббота<br>
с 10  до 18<br>
<?php echo $this->translate('Phone');?><span>+38 057 771 03 40<span><br>
<span>+38 067 84 29 675<span><br>
</p>
</div>
</div>
<div class="info2">
E-mail: <a href="office@apartment-kharkov.com">office@apartment-kharkov.com</a><br>
Сайт: <a class="un" href="http://www.apartment-kharkov.com.ua">www.apartment-kharkov.com.ua</a> <br><br>
Skype manager_apartment:<br><br>
<script type="text/javascript" src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js"></script>
<a href="skype:manager_apartment?call">
<img src="http://download.skype.com/share/skypebuttons/buttons/call_blue_white_124x52.png" style="border: none;" width="124" height="52" alt="Skype Me™!" /></a><br>

</div>
<div class="message"><?php echo $this->form;?></div>
<div class="info3"><hr>
<div class="inf4"><img src="/img/office8.jpg" alt=""></div>
<div class="inf4"><img src="/img/office2.jpg" alt=""></div>
<div class="inf4"><img src="/img/office_manager.jpg" alt=""></div>
</div>

</div>
</div>