<div id="you_here"><p><span><?php echo $this->translate('You are here')?></span>
<a href="/"><?php echo $this->translate('Home'); ?></a> / <?php echo $this->translate('Our city')?></p></div>
<div id="menu_view">
    <div id="line"></div>
</div>

<div class="pages">
    <div class="our_city">
 <?php
  if (Model_Lang::get() == 'rus')
 {
 ?> 
    <h2 class="zagmap">Харьков</h2>

    <p>
        <div class="photo1"><img src="/img/ua-map.jpg" alt="ukraine" /></div>
        <div class="photo1"><img src="/img/kh-map.jpg" alt="Kharkov" /></div>
    </p>

    <p>Харьков - административный центр Харьковской области, большой промышленный и культурный центр,
         значимый транспортный узел, второй по количеству населения город Украины (2005 г. - свыше 1,45 млн. жителей).</p>

    <p>
        <div class="ph2">
        <div class="photo2"><img src="/img/city10.jpg" alt="photo"></div>
        <div class="photo2"><img src="/img/city9.jpg" alt="photo"></div>
        <div class="photo2"><img src="/img/city8.jpg" alt="photo"></div>
        </div>
    </p>

    <p>
        <div class="photo2"><img src="/img/city5.jpg" alt="photo"></div>
        <div class="photo2"><img src="/img/city2.jpg" alt="photo"></div>
        <div class="photo2"><img src="/img/city11.jpg" alt="photo"></div>
    </p>

    <p>Город находится на северо-востоке Украины в долине рек Харьков, Лопань, Уди.
        В Харькове построено метро, состоящее из 3-х линий и общей протяженностью более 33 километров. 
        Город - большой промышленный центр. Развито машиностроение. Работают Харьковский завод транспортного машиностроения, 
        тракторный завод, металостроительный завод, станочностроительный завод, электротехнический, авиационный, турбинный, 
        велосипедный завод, электрогрузмаш и другие. Работают предприятия химической промышленности, строительных материалов, 
        производство мебели, деревообробка, полиграфические производства, пищевая промышленность. Работает парфюмернокосметическая 
        фабрика. Из легкой промышленности развита трикотажная, швейная, кожно-обувная, канатный завод. </p>

    <p>
        <div class="photo3"><img src="/img/city7.jpg" alt="photo"></div>
        <div class="photo3"><img src="/img/city3.jpg" alt="photo"></div>
    </p>
    <p> В городе действуют 30 высших учебных заведений. Крупнейшие - Харьковский Государственный Университет, 
        Харьковский Политехнический Институт, Харьковский Государственный Медицинский Институт.</p>
    
        <p>
        <div class="photo3"><img src="/img/city4.jpg" alt="photo"></div>
        <div class="photo3"><img src="/img/city6.jpg" alt="photo"></div>
    </p>

    <p>Действуют астрономическая обсерватория, 60 научно-исследовательских институтов, более 80-ти библиотек, 5 музеев, 
        21 кинотеатр, 6 театров, цирк, дворец спорта, дворец водных видов спорта, 32 стадиона. </p>
    
    <?php } 
    else { ?>
            <h2 class="zagmap">Kharkov</h2>

    <p>
        <div class="photo1"><img src="/img/ua-map.jpg" alt="ukraine" /></div>
        <div class="photo1"><img src="/img/kh-map.jpg" alt="Kharkov" /></div>
    </p>

    <p>Welcome to Kharkov, Ukraine! Here are plenty of things to do, plenty of things to see, plenty of things to be amazed by !</p>

    <p>
        <div class="ph2">
        <div class="photo2"><img src="/img/city10.jpg" alt="photo"></div>
        <div class="photo2"><img src="/img/city9.jpg" alt="photo"></div>
        <div class="photo2"><img src="/img/city8.jpg" alt="photo"></div>
        </div>
    </p>

    <p>
        <div class="photo2"><img src="/img/city5.jpg" alt="photo"></div>
        <div class="photo2"><img src="/img/city2.jpg" alt="photo"></div>
        <div class="photo2"><img src="/img/city11.jpg" alt="photo"></div>
    </p>

   <p>Kharkov was founded in the 17th century as a military garrison, this city in northeastern Ukraine was built on the edge 
        of the steppes, A legend tells that Kharkov got its name from a farmer Chariton, a.k.a. Kharko. Two rivers, 
        Lopan and Kharkov, flow through this city. The sea air is often brought here by westerly and southwesterly winds, 
        which makes its climate moderate continental, with prolonged but not severe winter. The summer is warm, sometimes hot. 
        Kharkov abounds in orchards, gardens and tree-lined avenues. According to the Kharkov meteorological service data 
        collected over many years:
        The average yearly t° is 6.9°C; ~ 44.6 F 
        The coldest months are January -7.1°C ~ 19F 
        and February -6.7°C ~ 20F; 
        The hottest months are July and August 30°C ~86F; 
        The yearly average month t° variation is 27.6°C;</p>

    <p>
        <div class="photo3"><img src="/img/city7.jpg" alt="photo"></div>
        <div class="photo3"><img src="/img/city3.jpg" alt="photo"></div>
    </p>
    <p> The Kharkov population is second after Kiev in Ukraine, and is now close to 1.5 million. Kharkov is a big (if not the biggest) center of science and culture in Ukraine. There are more than 60 scientific research institutes, more than 170 secondary education schools, more than 150 educational centers and special secondary education schools, the number of private and state owned higher education institutions has now reached 80. About 20,000 students graduate yearly from Kharkov higher education institutions. There are 49 cultural centers and institutions, among them 5 museums, a town art gallery, six major theatres. Nuclear power equipment, farm machinery, airplanes, and electronic devices typify the Karkov factory output.

Kharkov have celebrated its 350th anniversary soon. The city still has buildings that are 150 years old and more. They have the unique "old Russian" architecture style. There were many famous architects living and working in Kharkov. Kharkov features 40,000 hectares of parks and a lot of green space.

After World War I, the city served as Ukraine's capital. Many of its temples were destroyed during the Communist purges in the 1920-30s. Then came World War II, proving more devastating for Kharkov's people and cityscape. The Germans and Russians took turns occupying the city. Now Kharkov is rebuilt and we can admire it's fascinating architecture.</p>
    
    
        <p>
        <div class="photo3"><img src="/img/city4.jpg" alt="photo"></div>
        <div class="photo3"><img src="/img/city6.jpg" alt="photo"></div>
    </p>

     <p>Freedom Square is one of the largest in Europe. Concerts, meetings, trade fairs and other events take place here. The State Industry building is in the center of Freedom Square. It is a unique architectural and historical monument. It is the heart of the city. The State Industry building was the first skyscraper in the former U.S.S.R. It has being built from 1925-1928. It represents a group of buildings connected with passageways, which are on different stages. The total area takes 11 thousand square meters and the length of faзade is 300 meters.
Go up to the observation deck to get a view of the city. From there you'll be able to see the huge Memorial of Glory dedicated to the Ukrainians who died in the Great Patriotic War. Near the memorial, in a lovely park, is the statue known as the Mother of Ukraine. For fascinating people watching, be sure to drop by Kharkov's mineral-water wells, located at the western end of the park, next to the Hotel Mir. City residents go there to fill all kinds of containers with fresh drinking water. Pokrovsky Cathedral's stone bell tower is a prominent local landmark. Blagoveshensky Cathedral made in Eastern Baroque style from red and cream striped brick. It is also worth seeing a night performance at the city's Opera and Ballet Theater ( pictured below). </p>

<?php } ?>
</div>
</div>
