<p>New order:</p>

Apartment №: <?php echo $this->apartments->ID; ?> Adress <?php echo $this->apartments->get('adress'); ?>
Price: <?php echo $this->apartments->get('cost'); ?> per day
Arrival date: <?php echo $this->client_info->arrival; ?>
Departure date: <?php echo $this->client_info->departure; ?>
<?php if ($this->client_info->comment){?>
Comments: <?php echo $this->client_info->comment ?>
<?php } ?>
<?php if ($this->services){?>
Additional services:
<ul>
    <?php foreach ($this->services as $service){?>
        <li>
            <?php echo $service->get('name') ?>
        </li>
    <?php }?>
</ul>
<?php } ?>

Client: <?php echo $this->client_info->name ?>
E-mail: <?php echo $this->client_info->email ?>
Phone <?php echo $this->client_info->phone ?>