Dear <?php echo $this->client_info->name; ?>!<br>
Thank you for your request at Charming Apartments. It was successfully received. <br>
Here are details of your order: <br>
Apartment # <?php echo $this->apartments->ID; ?> Address <?php echo $this->apartments->get('adress'); ?><br>
Price $ <?php echo $this->apartments->get('cost'); ?> per day <br>
Arrival date: <?php echo $this->client_info->arrival; ?> <br>
Departure date: <?php echo $this->client_info->departure; ?><br>
<?php if ($this->client_info->comment){?>
Comments: <?php echo $this->client_info->comment ?><br>
<?php } ?>
<?php if ($this->services){?>
Additional services:<br>
<ul>
    <?php foreach ($this->services as $service){?>
        <li>
            <?php echo $service->get('name') ?>
        </li>
    <?php }?>
</ul>
<?php } ?><br>
Our manager will contact you within next 12 hours. <br>

All the best<br>
Charming Apartments<br>
<a href="www.apartment-kharkov.com.ua">apartment-kharkov.com.ua</a>
