Dear <?php echo $this->client_info->name; ?>!
Thank you for your request at Charming Apartments. It was successfully received. 
Here are details of your order:
Apartment # <?php echo $this->apartments->ID; ?> Address <?php echo $this->apartments->get('adress'); ?>
Price $ <?php echo $this->apartments->get('cost'); ?> per day
Arrival date: <?php echo $this->client_info->arrival; ?>
Departure date: <?php echo $this->client_info->departure; ?>
<?php if ($this->client_info->comment){?>
Comments: <?php echo $this->client_info->comment ?>
<?php } ?>
<?php if ($this->services){?>
Additional services:
<ul>
    <?php foreach ($this->services as $service){?>
        <li>
            <?php echo $service->get('name') ?>
        </li>
    <?php }?>
</ul>
<?php } ?>
Our manager will contact you within next 12 hours. 

All the best
Charming Apartments
www.apartment-kharkov.com 
