
    <div class="srv">
    <div class="ic_srv"><img src="/img/icon_service/<?php echo $this->model->imgic; ?>" title="<?php echo $this->model->get('text'); ?>" alt=""></div>
    <div class="choice1"><div class="check"><input type="checkbox" class="sl" name="choice[]" value="<?php echo $this->model->ID; ?>"></div></div>
    <div class="srv_text"><?php echo $this->model->get('name'); ?></div>
    </div>