<tr data-id="<?php echo $this->model->ID; ?>" class="<?php echo $this->model->published? 'success' : 'error'?>">
<!--<tr class="<?php echo $this->model->published? 'success' : 'error'?>">-->
    <td><?php echo $this->model->ID ;?></td>
    <td><?php echo $this->model->get('comment') ;?></td>
    <td><?php echo $this->model->get('adress') ;?></td>
    <td>
        <a href="/admin/apartments/edit/id/<?php echo $this->model->ID; ?>" title="Редактировать"><i class="icon-pencil"></i></a>
        <a href="/admin/apartments/edit-photos/id/<?php echo $this->model->ID; ?>" title="Редактировать фотографии"><i class="icon-th"></i></a>
        <a href="/admin/apartments/hide/id/<?php echo $this->model->ID; ?>" class="toggle-apart" title="<?php echo $this->model->published? 'Скрыть' : 'Показать' ?>"><i class="<?php echo $this->model->published? 'icon-eye-open' : 'icon-eye-close' ?>"></i></a>
        <a href="/admin/apartments/del/id/<?php echo $this->model->ID; ?>" class="remove-apart" title="Удалить"><i class="icon-remove"></i></a>
    </td>
</tr>
