<?php
//echo $this->text->text;
?>
    <div id="you_here"><p><span><?php echo $this->translate('You are here')?></span>
<a href="/"><?php echo $this->translate('Home'); ?></a> / <?php echo $this->translate('About us')?></p></div>
<div id="menu_view">
    <div id="line"></div>
</div>

<div class="pages">
    <?php //echo $this->text->get('text'); ?>
    
<div id="about">
<div class="about1">    
<div id="mapa"><img src="/img/map_rus.jpg" alt=""></div>
<div class="info1">
<p><span>Директор:</span><br>
Наталия Панкова</p>
<p><span>Менеджер:</span><br>
Татьяна, Кристина</p>
<p><span>Наш адрес:</span><br>
ул. Сумская 13,<br>
2-й этаж, офис 3<br>
Харьков<br> 
Украина<br><br>
</p>
<p><span>Мы работаем:</span><br>
Понедельник - суббота<br>
с 10  до 18<br>
тел. <span>+38 057 771 03 40<span><br>
<span>+38 067 84 29 675<span><br>
</p>
</div>
</div>
<div class="info2">

E-mail: director@apartment-kharkov.com <br>
Сайт: <a class="un" href="http://www.apartment-kharkov.com.ua">www.apartment-kharkov.com.ua</a> <br>
</div>
<div class="message">

Директор:
Наталия Панкова

Менеджер:
Татьяна, Кристина

Наш адрес:
ул. Сумская 13,
2-й этаж, офис 3
Харьков
Украина

Мы работаем:
Понедельник - суббота
с 10 до 18
тел. +38 057 771 03 40
+38 067 84 29 675
</div>
<div class="info3">
    <hr>
<div class="inf4"><img src="img/office8.jpg" alt=""></div>
<div class="inf4"><img src="img/office2.jpg" alt=""></div>
<div class="inf4"><img src="img/office_manager.jpg" alt=""></div>
</div>
</div>
</div>